---
title: "Example Interactive R Markdown Document"
output: 
  html_document: 
    highlight: tango
    theme: cosmo
runtime: shiny
---

```{r setup, message=FALSE}
library(ggplot2)
library(dplyr)
```

We got some car data!
```{r cars}
head(mtcars)
```

Let's (set up some function to) model cars!
```{r}
predictor_choices <- names(mtcars)[names(mtcars) != "mpg"]

fit_mtcars <- function(predictors) {
  mtcars_formula <- as.formula(paste0("mpg ~ ", paste(predictors, collapse = " + ")))
  lm(mtcars_formula, data = mtcars, y = TRUE)
}
```

Let's (interactively) look at our model!
```{r plot, echo = TRUE, fig.width = 8, fig.height = 8}
mtcars_lm <- reactive({
  fit_mtcars(input$predictors)
})
    
sidebarLayout(
  sidebarPanel(
    
    checkboxGroupInput("predictors", label = h4("Predictors"),
                       choices = predictor_choices, selected = "cyl"),
    
    selectInput("labels", label = h4("Labels"),
                choices = c("points", "text"), selected = "points"),
    
    renderText({
      paste("r² = ", round(summary(mtcars_lm())$adj.r.squared, 3))
    })
    
  ),
  
  mainPanel(
    
    renderPlot({
      
      req(input$predictors, input$labels)

      predicted_mtcars <- mtcars %>%
        mutate(car = rownames(mtcars))
      
      predicted_mtcars$predicted <- mtcars_lm()$fitted.values
      
      prediction_plot <- ggplot(predicted_mtcars,
                                aes(x = predicted, y = mpg, label = car)) + 
        geom_smooth(method = "lm") +
        scale_x_continuous(name = "Predicted MPG", limits = c(10, 35),
                           breaks = seq(10, 35, 5)) +
        scale_y_continuous(name = "MPG", limits = c(10, 35),
                           breaks = seq(10, 35, 5)) +
        theme_bw()
      
      if (input$labels == "points") {
        prediction_plot + geom_jitter()
      } else if (input$labels == "text") {
        prediction_plot + geom_label()
      }
      
    }, width = 600, height = 600)
  )
)
```
